#!/usr/bin/env python3
"""
Frontend Contract Generator

Generates TypeScript/JavaScript files from Python contracts.
Run this script whenever you update shared/api_endpoints.py or shared/constants.py

Also fetches and generates the latest agent version from GitHub releases.

Usage:
    python shared/generate_frontend_types.py

Output:
    - jarwisfrontend/src/config/endpoints.generated.js
    - jarwisfrontend/src/config/planLimits.generated.js
    - jarwisfrontend/src/config/constants.generated.js
    - jarwisfrontend/src/config/agentVersion.generated.js
"""

import os
import sys
import json
import urllib.request
import urllib.error
from pathlib import Path
from datetime import datetime

# Add parent directory to path
sys.path.insert(0, str(Path(__file__).parent.parent))

from shared.api_endpoints import ENDPOINT_GROUPS, APIEndpoints
from shared.constants import get_plan_limits_for_frontend, ScanTypes, SeverityLevels


def generate_endpoints_js() -> str:
    """Generate endpoints.js from Python definitions"""
    
    lines = [
        "// AUTO-GENERATED FILE - DO NOT EDIT MANUALLY",
        f"// Generated by shared/generate_frontend_types.py on {datetime.now().isoformat()}",
        "// Source: shared/api_endpoints.py",
        "",
        "/**",
        " * API Endpoints - Single Source of Truth",
        " * ",
        " * All endpoints are defined in Python (shared/api_endpoints.py)",
        " * and auto-generated to JavaScript.",
        " * ",
        " * To add a new endpoint:",
        " * 1. Add it to shared/api_endpoints.py",
        " * 2. Run: python shared/generate_frontend_types.py",
        " */",
        "",
        "// Base URL from environment",
        "export const API_BASE_URL = process.env.REACT_APP_API_URL || 'http://localhost:8000';",
        "",
    ]
    
    # Generate endpoint groups
    for group_name, group_data in ENDPOINT_GROUPS.items():
        prefix = group_data["prefix"]
        endpoints = group_data["endpoints"]
        
        lines.append(f"// ==================== {group_name} ====================")
        lines.append(f"export const {group_name} = {{")
        lines.append(f"  PREFIX: '{prefix}',")
        
        for endpoint_name, endpoint_path in endpoints.items():
            # Check if endpoint has parameters
            if "{" in endpoint_path:
                # Generate function for parameterized endpoints
                params = []
                path = endpoint_path
                import re
                for match in re.finditer(r'\{(\w+)\}', endpoint_path):
                    param_name = match.group(1)
                    params.append(param_name)
                
                param_list = ", ".join(params)
                # Convert {param} to ${param} for JS template literal
                js_path = re.sub(r'\{(\w+)\}', r'${\1}', endpoint_path)
                lines.append(f"  {endpoint_name}: ({param_list}) => `{prefix}{js_path}`,")
            else:
                lines.append(f"  {endpoint_name}: '{prefix}{endpoint_path}',")
        
        lines.append("};")
        lines.append("")
    
    # Generate helper functions
    lines.extend([
        "// ==================== HELPERS ====================",
        "",
        "/**",
        " * Build full URL with base",
        " */",
        "export const buildUrl = (endpoint) => {",
        "  if (endpoint.startsWith('http')) return endpoint;",
        "  return `${API_BASE_URL}${endpoint}`;",
        "};",
        "",
        "/**",
        " * Check if URL is an auth endpoint (skip session checks)",
        " */",
        "export const isAuthEndpoint = (url) => {",
        "  if (!url) return false;",
        "  const authPaths = [",
        "    AUTH.LOGIN,",
        "    AUTH.REGISTER,",
        "    AUTH.REFRESH,",
        "    HEALTH.CHECK,",
        "  ];",
        "  return authPaths.some(path => url.includes(path));",
        "};",
        "",
        "// Default export for convenience",
        "export default {",
    ])
    
    for group_name in ENDPOINT_GROUPS.keys():
        lines.append(f"  {group_name},")
    
    lines.extend([
        "  API_BASE_URL,",
        "  buildUrl,",
        "  isAuthEndpoint,",
        "};",
    ])
    
    return "\n".join(lines)


def generate_plan_limits_js() -> str:
    """Generate plan limits from Python definitions"""
    
    plan_limits = get_plan_limits_for_frontend()
    
    lines = [
        "// AUTO-GENERATED FILE - DO NOT EDIT MANUALLY",
        f"// Generated by shared/generate_frontend_types.py on {datetime.now().isoformat()}",
        "// Source: shared/constants.py",
        "",
        "/**",
        " * Plan Limits - Single Source of Truth",
        " * ",
        " * All plan configurations are defined in Python (shared/constants.py)",
        " * and auto-generated to JavaScript.",
        " */",
        "",
        f"export const PLAN_LIMITS = {json.dumps(plan_limits, indent=2)};",
        "",
        "// Helper to get plan by ID",
        "export const getPlan = (planId) => PLAN_LIMITS[planId?.toLowerCase()] || PLAN_LIMITS.free;",
        "",
        "// Check if plan has feature",
        "export const hasFeature = (planId, feature) => {",
        "  const plan = getPlan(planId);",
        "  return plan?.features?.[feature] || false;",
        "};",
        "",
        "// Get remaining scans",
        "export const getRemainingScans = (planId, usedScans) => {",
        "  const plan = getPlan(planId);",
        "  if (plan.maxScansPerMonth >= 999999) return Infinity;",
        "  return Math.max(0, plan.maxScansPerMonth - usedScans);",
        "};",
        "",
        "// Get remaining tokens",
        "export const getRemainingTokens = (planId, usedTokens) => {",
        "  const plan = getPlan(planId);",
        "  if (plan.tokensPerMonth >= 999999) return Infinity;",
        "  return Math.max(0, plan.tokensPerMonth - usedTokens);",
        "};",
        "",
        "export default PLAN_LIMITS;",
    ]
    
    return "\n".join(lines)


def fetch_latest_agent_version() -> dict:
    """Fetch latest agent release info from GitHub API"""
    
    GITHUB_API_URL = "https://api.github.com/repos/sureshdevrari/jarwis-agent/releases/latest"
    
    # Default fallback values
    fallback = {
        "version": "2.1.9",
        "tag_name": "v2.1.9",
        "release_date": datetime.now().strftime("%Y-%m-%d"),
        "fetched_from": "fallback"
    }
    
    try:
        req = urllib.request.Request(
            GITHUB_API_URL,
            headers={
                "Accept": "application/vnd.github.v3+json",
                "User-Agent": "JarwisFrontendGenerator/1.0"
            }
        )
        
        with urllib.request.urlopen(req, timeout=10) as response:
            data = json.loads(response.read().decode())
            
            tag_name = data.get("tag_name", fallback["tag_name"])
            version = tag_name.lstrip("v")
            published_at = data.get("published_at", "")
            release_date = published_at[:10] if published_at else fallback["release_date"]
            
            return {
                "version": version,
                "tag_name": tag_name,
                "release_date": release_date,
                "fetched_from": "github_api"
            }
            
    except (urllib.error.URLError, urllib.error.HTTPError, json.JSONDecodeError, Exception) as e:
        print(f"  ⚠ Could not fetch from GitHub API: {e}")
        print(f"  ⚠ Using fallback version: {fallback['version']}")
        return fallback


def generate_agent_version_js() -> str:
    """Generate agent version config from GitHub releases"""
    
    version_info = fetch_latest_agent_version()
    
    lines = [
        "// AUTO-GENERATED FILE - DO NOT EDIT MANUALLY",
        f"// Generated by shared/generate_frontend_types.py on {datetime.now().isoformat()}",
        f"// Source: GitHub API (sureshdevrari/jarwis-agent) - {version_info['fetched_from']}",
        "",
        "/**",
        " * Agent Version Configuration",
        " * ",
        " * This file is auto-generated at build time by fetching the latest",
        " * release from GitHub. The fallback values here are current as of",
        " * the last build.",
        " */",
        "",
        f"export const AGENT_VERSION = '{version_info['version']}';",
        f"export const AGENT_TAG_NAME = '{version_info['tag_name']}';",
        f"export const AGENT_RELEASE_DATE = '{version_info['release_date']}';",
        "",
        "// GitHub release base URL",
        f"export const GITHUB_RELEASE_BASE = `https://github.com/sureshdevrari/jarwis-agent/releases/download/${{AGENT_TAG_NAME}}`;",
        "",
        "// Download URLs for each platform",
        "export const DOWNLOAD_URLS = {",
        "  windows: {",
        "    gui: `${GITHUB_RELEASE_BASE}/JarwisAgentSetup-GUI.exe`,",
        "    exe: `${GITHUB_RELEASE_BASE}/jarwis-agent.exe`,",
        "    msi: `${GITHUB_RELEASE_BASE}/JarwisAgent-${AGENT_VERSION}.msi`,",
        "    inno: `${GITHUB_RELEASE_BASE}/JarwisAgentSetup-${AGENT_VERSION}.exe`,",
        "  },",
        "  macos: {",
        "    dmg: `${GITHUB_RELEASE_BASE}/JarwisAgentSetup-${AGENT_VERSION}.dmg`,",
        "    pkg: `${GITHUB_RELEASE_BASE}/JarwisAgent-${AGENT_VERSION}.pkg`,",
        "    binary: `${GITHUB_RELEASE_BASE}/jarwis-agent-macos`,",
        "  },",
        "  linux: {",
        "    deb: `${GITHUB_RELEASE_BASE}/jarwis-agent_${AGENT_VERSION}_amd64.deb`,",
        "    rpm: `${GITHUB_RELEASE_BASE}/jarwis-agent-${AGENT_VERSION}.x86_64.rpm`,",
        "    tarball: `${GITHUB_RELEASE_BASE}/jarwis-agent-${AGENT_VERSION}-linux.tar.gz`,",
        "    binary: `${GITHUB_RELEASE_BASE}/jarwis-agent-linux`,",
        "  },",
        "};",
        "",
        "export default {",
        "  AGENT_VERSION,",
        "  AGENT_TAG_NAME,",
        "  AGENT_RELEASE_DATE,",
        "  GITHUB_RELEASE_BASE,",
        "  DOWNLOAD_URLS,",
        "};",
    ]
    
    return "\n".join(lines)


def generate_constants_js() -> str:
    """Generate constants from Python definitions"""
    
    lines = [
        "// AUTO-GENERATED FILE - DO NOT EDIT MANUALLY",
        f"// Generated by shared/generate_frontend_types.py on {datetime.now().isoformat()}",
        "// Source: shared/constants.py",
        "",
        "/**",
        " * Shared Constants",
        " */",
        "",
        "// Scan Types",
        "export const SCAN_TYPES = {",
    ]
    
    for scan_type in ScanTypes:
        lines.append(f"  {scan_type.name}: '{scan_type.value}',")
    
    lines.extend([
        "};",
        "",
        "// Severity Levels",
        "export const SEVERITY_LEVELS = {",
    ])
    
    for severity in SeverityLevels:
        lines.append(f"  {severity.name}: '{severity.value}',")
    
    lines.extend([
        "};",
        "",
        "// Severity colors for UI",
        "export const SEVERITY_COLORS = {",
        "  critical: '#dc2626',  // red-600",
        "  high: '#ea580c',      // orange-600",
        "  medium: '#ca8a04',    // yellow-600",
        "  low: '#2563eb',       // blue-600",
        "  info: '#6b7280',      // gray-500",
        "};",
        "",
        "// Session settings",
        "export const SESSION = {",
        "  ACCESS_TOKEN_EXPIRE_SECONDS: 900,  // 15 minutes",
        "  REFRESH_BUFFER_SECONDS: 60,        // Refresh 1 min before expiry",
        "  INACTIVITY_TIMEOUT_MS: 3 * 60 * 60 * 1000,  // 3 hours",
        "};",
        "",
        "// Token storage keys",
        "export const STORAGE_KEYS = {",
        "  ACCESS_TOKEN: 'jarwis_access_token',",
        "  REFRESH_TOKEN: 'jarwis_refresh_token',",
        "  USER: 'jarwis_user',",
        "  TOKEN_EXPIRY: 'jarwis_token_expiry',",
        "  LAST_ACTIVITY: 'jarwis_last_activity',",
        "};",
        "",
        "export default {",
        "  SCAN_TYPES,",
        "  SEVERITY_LEVELS,",
        "  SEVERITY_COLORS,",
        "  SESSION,",
        "  STORAGE_KEYS,",
        "};",
    ])
    
    return "\n".join(lines)


def main():
    """Generate all frontend files"""
    
    # Determine paths
    script_dir = Path(__file__).parent
    project_root = script_dir.parent
    frontend_config = project_root / "jarwisfrontend" / "src" / "config"
    
    # Ensure directory exists
    frontend_config.mkdir(parents=True, exist_ok=True)
    
    # Generate files
    files_to_generate = [
        ("endpoints.generated.js", generate_endpoints_js()),
        ("planLimits.generated.js", generate_plan_limits_js()),
        ("constants.generated.js", generate_constants_js()),
        ("agentVersion.generated.js", generate_agent_version_js()),
    ]
    
    print("=" * 60)
    print("Frontend Contract Generator")
    print("=" * 60)
    
    for filename, content in files_to_generate:
        filepath = frontend_config / filename
        with open(filepath, "w", encoding="utf-8") as f:
            f.write(content)
        print(f"✓ Generated: {filepath.relative_to(project_root)}")
    
    print("")
    print("=" * 60)
    print("IMPORTANT: Update your imports to use generated files:")
    print("")
    print("  // Old (manual):")
    print("  import { PLAN_LIMITS } from './config/planLimits';")
    print("")
    print("  // New (auto-generated):")
    print("  import ENDPOINTS from './config/endpoints.generated';")
    print("  import { PLAN_LIMITS } from './config/planLimits.generated';")
    print("  import { SCAN_TYPES } from './config/constants.generated';")
    print("=" * 60)


if __name__ == "__main__":
    main()
